### ISSUE TITLE
Unclear that GraphQL required from docs

### ISSUE THREAD

**Issue by Dangoo** [storyofams/storyblok-toolkit#11]
Hey there, first of all thanks for publishing this package! I'm currently working on a project using Next.js and Storyblok and went though all the Storyblok Bridge setup when I found this project. And from what I can tell from the APIs it looks great!

**Describe the bug**
The catch is, that I was not able to test it out right away, since I got the following error after installing and using the `Image` component:
```
./node_modules/@storyofams/storyblok-toolkit/dist/createIntersectionObserver-501bd296.js:1:61
Module not found: Can't resolve 'graphql/language/printer'
null
```

**To Reproduce**

```tsx
// pages/index.tsx

import React from 'react'
import type { NextPage } from 'next'
import type { StoryData } from 'storyblok-js-client'

const HomePage: NextPage<{ story: StoryData; preview: boolean }> = (
  props
): JSX.Element => {
  return (
      <Image
        src="https://a.storyblok.com/f/…/128x64/1234567/foo.jpg"
        width="128"
      />
  )
}
```

1. Create a node project
2. Install nextjs and storyblok-toolkit
3. Run `next dev`

**Expected behavior**
From only the following documentation line I did not expect, that GraphQL is a required dependency:
> We also provide an easy way to configure a GraphQL client, an optimized image component and some utility functions.

But even installing a required peer dependency `graphql-request` manually (thats me just too lazy to upgrade to npm@7… yet) still brought the above error. Of course installing `graphql` after that made it work.

I'm not sure why GraphQL is needed for using the image component, but maybe it would help to add to the docs that it is required to operate the package?
**Update**: Found it is documented for `getClient`:
https://storyblok-toolkit.vercel.app/docs/api/getClient#getclient

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 91

**Comment by BJvdA** [comment]
Thanks for bug report. It's not intended that `graphql` is required to use the Image component, it should only be required for `getClient`, so something must be going wrong with bundling/exporting. I'll look into fixing it!

**Comment by BJvdA** [comment]
I did some testing, and I think there is no (easy) way to prevent needing graphql when using the Image component because of commonjs. I've added it as a peerDependency, so you shouldn't get this error anymore. Also if you only use `Image`, your bundler should be able to treeshake graphql out of your bundle 🤞
