### ISSUE TITLE
[TS] Export interface ImageProps

### ISSUE THREAD

**Issue by Dangoo** [storyofams/storyblok-toolkit#12]
**Is your feature request related to a problem? Please describe.**
Using the `Image` component inside other components might require to pass some props of interface `ImageProps`. But other than for `GetImagePropsOptions`, `ImageProps` is not getting exported:

https://github.com/storyofams/storyblok-toolkit/blob/master/src/image/Image.tsx#L9

**Describe the solution you'd like**
Export `ImageProps`

Would you be open for a PR?

**Comment by BJvdA** [comment]
Must have missed it, PR is welcome
