### ISSUE TITLE
Proposal: Onload Event for Image Component

### ISSUE THREAD

**Issue by Dangoo** [storyofams/storyblok-toolkit#14]
**Is your feature request related to a problem? Please describe.**
The current approach fetching a lower resolution image while the actual sources are loaded works well. But if you want to customize the loading behavior, lets say by fading the image in as soon as it enters the viewport, it is not possible to get notified about the image source being loaded (nor IntersectionObservers `isIntersecting` property).

**Describe the solution you'd like**
Finding a way to expose the loading API from `Image`:
https://github.com/storyofams/storyblok-toolkit/blob/38359e73a97f5c94bd9215d6e668407e3a51413b/src/image/Image.tsx#L56

One way to achieve this could be to extend `ImageProps` interface by `onLoad` callback and call it together with `useImageLoader.onload`.

This would make it possible to interact with the image in a way like this:

```typescript
export const CustomImage = ({src}) => {
  const [loaded, setLoaded] = useState(false)
  const handleLoad = useCallback(() => {
    setLoaded(true)
  }, [setLoaded])

  return <Image className={`image ${loaded && 'image--loaded'}`} src={src} onLoad={handleOnLoad} />
}
```

Let me know what you think! :)

**Comment by BJvdA** [comment]
Thanks for the suggestion! Seems like a good addition, so I've added it
