### ISSUE TITLE
[Image] Error with filter parameter concatenation

### ISSUE THREAD

**Issue by Dangoo** [storyofams/storyblok-toolkit#17]
**Describe the bug**
Following [this guide](https://www.storyblok.com/docs/image-service) the Storyblok Image Service provides one argument for filters (e.g. `focus`, `fill` and `format`).

The issue is, that the `Image` component from this package is doing URL concatenation in at least two places: `getImageProps` and `Picture`. For the latter some regex should parse existing filters and append `format(webp)` if feasible:
https://github.com/storyofams/storyblok-toolkit/blob/897a9d25ab6ee56e33a4fc06d0ed626621b35ec6/src/image/Picture.tsx#L54-L57

But when passing the `focus` option for `Image` the filter arguments are not joined into one parameter but concatenated:
```
http://img2.storyblok.com/filters:focal(920x625:921x626)/filters:format(webp):format(webp)/f/<ID>/1532x1024/<UID>/test.jpg
```

Note the doubled `filters:format(webp):format(webp)` and `filters:focal(920x625:921x626)/filters…`

**To Reproduce**
1. Use Image component
2. Pass `<Image focus="920x625:921x626" fluid={1200} ... />`
4. See error:
`test.jpg:1 GET http://img2.storyblok.com/filters:focal(920x625:921x626)/filters:format(webp):format(webp)/f/<ID>/1532x1024/<UID>/test.jpg 404 (Not Found)`

**Expected behavior**
The filters should all be concatenated into a single param and contain no duplication:
`filters:focal(920x625:921x626):format(webp)`

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 91
 - Package Version: 1.6.0

**Comment by Dangoo** [comment]
Added a draft PR #18 containing some tests to reproduce the issue and as base for a potential fix.
Not sure whether just fixing the RegEx or refactoring `filters` parsing and merging (e.g. as util function) would be the way to go?

**Comment by BJvdA** [comment]
Thanks for catching this! I think I have it fixed in `fix/picture-filters`, could you change your tests PR to merge into that branch?

**Comment by Dangoo** [comment]
@BJvdA redirected #18 to your branch #19
