### ISSUE TITLE
Use latest Storyblok bridge

### ISSUE THREAD

**Issue by selrond** [storyofams/storyblok-toolkit#33]
Is there a reason this package uses storyblok v1 bridge?

https://github.com/storyofams/storyblok-toolkit/blob/3bae06ab0c6c5d1c4b74e82c7395077994ffa476/src/bridge/init.ts#L6

More info about v2: [Storyblok Bridge V2 Beta - Storyblok](https://www.storyblok.com/cl/storyblok-bridge-v2-beta "Storyblok Bridge V2 Beta - Storyblok")

**Comment by BJvdA** [comment]
We are waiting for the v2 bridge to come out of beta first, in the meantime you can try it on the `beta` branch.
