### ISSUE TITLE
Images are not responsive

### ISSUE THREAD

**Issue by fcisio** [storyofams/storyblok-toolkit#6]
**Describe the bug**
Hi, I find this package pretty interesting and so I'm trying it out.

I noticed that the images are not actually responsive, so I'm wondering if I'm missing something or if it's a bug.

Basically, the `srcset` gets generated, but all the images it contains are the same dimentions.

**To Reproduce**

```jsx
<Image
  src={storyblok_image?.filename}
  fluid={696}
  alt={storyblok_image?.alt}
  width="100%"
/>
```

**Expected behavior**
The `scrset` should be generated, and the images should have different dimensions for each breakpoint

**Screenshots**
![ScreenShot 2021-05-20 at 6 43 23 PM](https://user-images.githubusercontent.com/46095852/119057933-66298a80-b99b-11eb-9009-e51a38f2db60.png)

**Comment by BJvdA** [comment]
Hi,

It looks a bit confusing, but the actual sizes are in the url before the `/smart` part, the red lines are the original size which are part of the url returned by Storyblok. Please see below in green:

![119057933-66298a80-b99b-11eb-9009-e51a38f2db60](https://user-images.githubusercontent.com/9120530/119111314-3e7e0500-ba23-11eb-8851-00223731cea4.png)

**Comment by fcisio** [comment]
You're right, my bad.
I was testing on a retina display, so I was only getting a single file. On a regular display, I'm able to see the different sizes load.

Thanks

**Comment by BJvdA** [comment]
No problem, you're welcome!
